# Generated by Django 3.2.21 on 2023-12-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendMessage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('parent_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('teacher_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('subject', models.CharField(blank=True, max_length=25, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('time_info', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'evaluate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('address_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'parent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParMoney',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('parent_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('account_money', models.CharField(blank=True, max_length=25, null=True)),
                ('balance', models.CharField(blank=True, max_length=25, null=True)),
                ('points', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'par_money',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParOrder',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('parent_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('book_name', models.CharField(blank=True, max_length=25, null=True)),
                ('quantity', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.CharField(blank=True, max_length=25, null=True)),
                ('is_received', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'par_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParReward',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('parent_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('voucher_value', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'par_reward',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('parent_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('plan_content', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'plant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('parent_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('teacher_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=25, null=True)),
                ('subject', models.CharField(blank=True, max_length=25, null=True)),
                ('reserve_time', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'reserve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('teaching_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
